apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server
  namespace: app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: app-server
  template:
    metadata:
      labels:
        app: app-server
    spec:
      nodeSelector:
        role: app
      containers:
      - name: app-server
        image: yoonhyemi/app-server
        envFrom:
        - secretRef:
            name: app-secret
        resources:
          requests:
            memory: "350Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "2"
        ports:
        - containerPort: 8080