apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-server-hpa
  namespace: app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-server
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource: # CPU 사용률 70% 도달 시 Pod 수 늘리기
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50 # 사용률(%) = (현재 Pod의 CPU 사용량 (mCPU) / requests.cpu) * 100