name: Build and Push Docker Image - CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'termurin'

      - name: Navigate to demo directory
        run: cd demo
      
      - name: Build Spring Boot application with Gradle
        run: ./gredlew build -x test
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: ~/.cache/docker
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/app:latest

      - name: Set up kubectl
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up kubectl context
        run: |
          gcloud container clusters get-credentials your-cluster-name \
            --zone your-cluster-zone \
            --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Sync ArgoCD app
        run: |
          argocd app sync test-app
          argocd app wait test-app --timeout 300