name: Build and Push Docker Image - CI

on:
  push:
    branches:
      - main

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      
      - name: Build Spring Boot application with Gradle
        run: |
          cd demo
          chmod +x gradlew
          ./gradlew build -x test
      
      - name: Build Docker Image
        run: |
          cd demo
          COMMIT_SHA=${GITHUB_SHA::7}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/app-server:${COMMIT_SHA} .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          COMMIT_SHA=${GITHUB_SHA::7}
          docker push ${{ secrets.DOCKER_USERNAME }}/app-server:${COMMIT_SHA}

  run-docker-image-on-gke:
    needs: build-docker-image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up ArgoCD CLI
        run: |
          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/download/v2.6.0/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd

      - name: ArgoCD Login
        run: argocd login ${{ secrets.ARGOCD_SERVER }} --username ${{ secrets.ARGOCD_USERNAME }} --password ${{ secrets.ARGOCD_PASSWORD }} --insecure

      - name: Sync ArgoCD app
        run: |
          argocd app sync test-app
          argocd app wait test-app --timeout 300
